graph TD
    DS["data structures"] --> PR[primitive]
    DS --> NP["non-primitive"]
    PR --> I[int]
    PR --> F[float]
    PR --> C[char]
    PR --> P[pointer]
    NP --> A[arrays]
    NP --> L[lists]
    NP --> FI[files]
    L --> LI[linear]
    L --> NL["non-linear"]
    LI --> S[stack]
    LI --> Q[queue]
    NL --> G[graph]
    NL --> T[tree]
